Repository Niarit/ask-mate-python, pull requests merged in 2019-11, with the labels that each got.

#6 Implement tag page
  DAL/tags.py
  DAL/users.py
  data_handler.py
  server.py
  templates/question/display_one.html
  templates/tag/display_all.html
Labels: enhancement

#7 Add create time to user table
  sample_data/askmatepart2-sample-data.sql
Labels: bug

#9 Enable to accept an aswer as solution
  DAL/accepted_answers.py
  DAL/answers.py
  DAL/questions.py
  data_handler.py
  sample_data/askmatepart2-sample-data.sql
  server.py
  static/img/checked-checkmark.png
  static/img/unchecked-checkmark.png
  templates/question/display_one.html
Labels: enhancement

#10 Show name of the user after every question, answer and comment + Authorization
  DAL/answers.py
  DAL/comments.py
  DAL/questions.py
  data_handler.py
  server.py
  templates/question/display_all.html
  templates/question/display_five.html
  templates/question/display_one.html
  templates/user/login.html
Labels: enhancement

#12 Fill the databse with users and user ids
  sample_data/askmatepart2-sample-data.sql
  templates/question/display_one.html
Labels: enhancement, fix

#14 Prevent adding tag with empty name
  data_handler.py
Labels: fix

#15 Implement user reputation
  data_handler.py
  sample_data/askmatepart2-sample-data.sql
Labels: enhancement

#16 Feature/show users activity
  DAL/answers.py
  DAL/comments.py
  DAL/questions.py
  DAL/users.py
  data_handler.py
  sample_data/askmatepart2-sample-data.sql
  server.py
  static/style.css
  templates/user/user_page.html
Labels: enhancement

#17 Fix Users table ID next value for insert
  sample_data/askmatepart2-sample-data.sql
Labels: fix

#19 Replace 'if' authentication check with decorator
  server.py
Labels: enhancement

#20 Dev/validation
  data_handler.py
  server.py
  templates/error_messages.html
  templates/question/create.html
  templates/question/display_five.html
  templates/search/search_result.html
  validate.py
Labels: enhancement, fix

#22 Prevent SQL injecting in the sorting questions endpoint
  data_handler.py
Labels: fix
